version: "3.8"
services:
  ioc:
    image: lnls/${IOC_REPO}:${COMMIT}-base-3.15-debian-9.13
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.revision: ${COMMIT}
        org.opencontainers.image.source: https://github.com/${IOC_GROUP}/${IOC_REPO}.git
      args:
        IOC_GROUP: ${IOC_GROUP}
        IOC_REPO: ${IOC_REPO}
        COMMIT: ${COMMIT}


